name 'chef-freebsd-ipfw'
maintainer 'Steve King'
maintainer_email ''
license 'mit'
description 'Installs/Configures chef-freebsd-ipfw'
long_description 'Installs/Configures chef-freebsd-ipfw'
version '0.1.0'
